### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by duramato** [frdmn/znc-logviewer#7]
```
$ sudo npm install

> gifsicle@0.1.7 postinstall /home/logui/znc-logviewer/node_modules/gifsicle
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/gifsicle-bin/v0.1.7/vendor/linux/x64/gifsicle',
  name: 'gifsicle',
  os: 'linux',
  arch: 'x64' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /home/logui/znc-logviewer/node_modules/download/index.js:35:43
    at each (/home/logui/znc-logviewer/node_modules/each-async/each-async.js:63:4)
    at module.exports (/home/logui/znc-logviewer/node_modules/download/index.js:33:5)
    at /home/logui/znc-logviewer/node_modules/bin-wrapper/index.js:108:20
    at /home/logui/znc-logviewer/node_modules/bin-wrapper/index.js:141:24
    at /home/logui/znc-logviewer/node_modules/bin-check/index.js:30:20
    at /home/logui/znc-logviewer/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:112:15)
npm WARN znc-logviewer@0.0.1 No repository field.
npm WARN znc-logviewer@0.0.1 No license field.
npm ERR! Linux 2.6.32-042stab113.21
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@0.1.7 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gifsicle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/logui/znc-logviewer/npm-debug.log
```

**Comment by frdmn** [comment]
I guess the reason were the outdated (last commit "1 Oct 2014" 🙈 ) dependencies. I just pushed a fix for this to the `master` branch. Can you pull and retry?

BTW, this project was pretty much never finished - don't expect things work like expected
